[package]
name = "lool"
version = "0.0.1"
edition = "2021"
description = "🧳 lool » lucode.ar rust common utilities"
authors = ["Lucas Colombo <lucas@lucode.ar>"]

[profile.release]
strip = true
lto = true
codegen-units = 16
opt-level = 'z'
panic = "abort"
rpath = false
overflow-checks = false
debug = 0
debug-assertions = false

[registry]
default = "gitea"

[registries.gitea]
index = "sparse+http://lugit.local/api/packages/lucodear/cargo/"

[lib]
path = "lib/lib.rs"

[dependencies]
bitflags = "2.5.0"
eyre = { version = "0.6.12", default-features = false }
