[package]
name = "lool"
version = "0.0.5"
edition = "2021"
description = "🧳 lool » lucode.ar rust common utilities"
authors = ["Lucas Colombo <lucas@lucode.ar>"]

[profile.release]
strip = true
lto = true
codegen-units = 16
opt-level = 'z'
panic = "abort"
rpath = false
overflow-checks = false
debug = 0
debug-assertions = false

[lib]
path = "lib/lib.rs"

[features]
cli-stylize = ["dep:bitflags"]
logger = ["dep:log"]
macros = []
sched = ["dep:chrono"]
sched-tokio = ["dep:tokio", "tokio?/time", "tokio?/rt"]
sched-rule-recurrent = []
sched-rule-cron = []


[dependencies]
# default
eyre = { version = "0.6.12", default-features = false }

# optional
bitflags = { version = "2.5.0", optional = true }
chrono = { version = "0.4.37", optional = true }
log = { version = "0.4.21", optional = true }
tokio = { version = "1.37.0", optional = true }
num-traits = "0.2.18"


