[package]
name = "lool"
version = "0.0.5"
edition = "2021"
description = "🧳 lool » lucode.ar rust common utilities"
authors = ["Lucas Colombo <lucas@lucode.ar>"]

[profile.release]
strip = true
lto = true
codegen-units = 16
opt-level = 'z'
panic = "abort"
rpath = false
overflow-checks = false
debug = 0
debug-assertions = false

[lib]
path = "lib/lib.rs"

[features]
cli-stylize = ["dep:bitflags"]
logger = ["dep:log"]
macros = []

[dependencies]
bitflags = { version = "2.5.0", optional = true }
log = { version = "0.4.21", optional = true }
eyre = { version = "0.6.12", default-features = false }

