# https://taskfile.dev

version: '3'

tasks:
  run:watch:
    desc: 🚀 watch lool
    cmds:
      - cargo watch -c -x "run -- --version"

  build:watch:
    desc: 🚀 watch lool «build»
    cmds:
      - cargo watch -c -x "build"

  build:
    desc: ⚡ build lool «release»
    cmds:
      - cargo build --release
      - python check_size.py

  example:logger:
    desc: 🚀 run lool «example logger»
    cmds:
      - cargo run --example=logger --release --features logger
  
  example:threadpool:
    desc: 🚀 run lool «example threadpool»
    cmds:
      - cargo run --example=threadpool --release --features utils.threads

  fmt:
    desc: 🎨 format lool
    cmds:
      - cargo +nightly fmt --all

  lint:
    desc: 🧶 lint lool
    cmds:
      - cargo clippy --fix --all-features --allow-staged

  test:
    desc: 🧪 test lool
    cmds:
      - cargo nextest run --all-features

  release:patch:
    desc: 🚀 release «patch» version of lool
    deps:
        - release:pre
    cmds:
        - cargo release patch --execute --no-confirm
  
  release:minor:
    desc: 🚀 release «minor» version of lool
    deps:
        - release:pre
    cmds:
        - cargo release minor --execute --no-confirm

  release:major:
    desc: 🚀 release «major» version of lool
    deps:
        - release:pre
    cmds:
        - cargo release major --execute --no-confirm

  release:
      aliases:
        - "publish"
      desc: 🚀 release «patch» version of lool
      deps:
          - release:pre
      cmds:
          - cargo release patch --execute